# Generated by Django 3.1 on 2021-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='postpics')),
                ('target', models.CharField(max_length=100)),
                ('sarcasm', models.IntegerField()),
                ('sentiment', models.CharField(max_length=20)),
                ('stance', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
