# Generated by Django 3.1 on 2021-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210401_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
