# Generated by Django 3.1 on 2021-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210401_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sarcasm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
